grpc_server:
  socket_path: "/tmp/mapper_dmi.sock"

common:
  name: "arduino-mapper"
  version: "v1.13.0"
  api_version: "v1.0.0"
  protocol: "modbus-tcp"
  address: "127.0.0.1"
  http_port: "7777"
  edgecore_sock: /var/lib/kubeedge/kubeedge.sock

database:
  mysql:
    enabled: true         # 关键：启用
    addr: "127.0.0.1"     # 主机，不带端口
    database: "testdb"
    username: "mapper"    # 密码从环境变量读取